### PR TITLE
GET request in bandsv

### LINKED ISSUE #433: Add GET /request in bandsv
Implement GET `/request` in bandsv and fix
```json
{
     "error": {
          "code": -32603, 
          "data": "runtime error: invalid memory address or nil pointer dereference",
          "message": "Internal error"
     },
     "id": "",
     "jsonrpc": "2.0"
}
```

[Specification](https://documenter.getpostman.com/view/10283798/SWTEcbUC?version=latest)

### PR DESCRIPTION
**Pull request by evilpeach**
Fixes #433

### CODE REVIEW

File: chain/cmd/bandsv/main.go [hunk 1]
```diff
@@ -301,6 +301,27 @@ func handleStore(c *gin.Context) {
...
+		return
+	}
+	var body map[string]interface{}
+	err = json.Unmarshal(resp.Bytes(), &body)
+	if err == nil {
+		c.JSON(resp.StatusCode, body)
+	} else {
+		c.JSON(resp.StatusCode, resp.Bytes())
+	}
+	return
```
Comment (sorawit) [inline chain/cmd/bandsv/main.go]: Remove this

**Review by sorawit — CHANGES_REQUESTED** [review]

File: chain/cmd/bandsv/main.go [hunk 2]
```diff
@@ -301,6 +301,26 @@ func handleStore(c *gin.Context) {
...
+	resp, err := grequests.Get(
+		fmt.Sprintf(`%s/zoracle/request/%s`, queryURI, requestId),
+		nil,
+	)
+	if err != nil {
+		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
+		return
+	}
+	var body map[string]interface{}
+	err = json.Unmarshal(resp.Bytes(), &body)
```
Comment (taobun) [inline chain/cmd/bandsv/main.go]: I prefer using response 's method `resp.JSON(&body)`.

**Review by taobun — CHANGES_REQUESTED** [review]

**Review by taobun — APPROVED** [review]
lgtm

**Review by sorawit — APPROVED** [review]
