### PR TITLE
Oracled handle failed data source execution

### LINKED ISSUE #1836: Oracled handle failed data source execution
There are many cases that failed after data source execution. We need to define exit code for run oracle script

- Execution return empty output
- Execution return error exit code/ error request code

### PR DESCRIPTION
**Pull request by Benzbeeb**
Fixed #1836

### CODE REVIEW

File: chain/cmd/bandoracled2/executor.go [hunk 1]
```diff
@@ -16,16 +16,51 @@ type lambdaExecutor struct {
...
+
+	if err != nil {
+		l.Error(":skull: LambdaExecutor failed with error: %s", err.Error())
+		return []byte("EXECUTION_ERROR"), 255
+	}
+
+	if r.Returncode == 0 {
+		return []byte(r.Stdout), r.Returncode
+	} else {
+		return []byte{}, r.Returncode
```
Comment (taobun) [inline chain/cmd/bandoracled2/executor.go]: Log stderr here

**Review by taobun — CHANGES_REQUESTED** [review]

**Review by perimeko — DISMISSED** [review]

File: chain/cmd/bandoracled2/executor_test.go [hunk 2]
```diff
@@ -0,0 +1,106 @@
...
+	"net/http"
+	"net/http/httptest"
+	"testing"
+	"time"
+
+	"github.com/stretchr/testify/require"
+	"github.com/tendermint/tendermint/libs/log"
+)
+
+func creatDeafaultServer() *httptest.Server {
```
Comment (sorawit) [inline chain/cmd/bandoracled2/executor_test.go]: Default

**Review by sorawit — CHANGES_REQUESTED** [review]

**Review by perimeko — APPROVED** [review]
