### PR TITLE
Handle failed transaction in cacher

### LINKED ISSUE #1010: Handle failed transaction in cacher
Failed transactions should not just be ignored, though actions can be left empty.

### PR DESCRIPTION
**Pull request by Benzbeeb**
Fixed #1010

### CODE REVIEW

File: chain/app/db_app.go [hunk 1]
```diff
@@ -156,7 +156,19 @@ func (app *dbBandApp) DeliverTx(req abci.RequestDeliverTx) (res abci.ResponseDel
 		// Add involved accounts
 		involvedAccounts := stdTx.GetSigners()
 		if !res.IsOK() {
-			// TODO: We should not completely ignore failed transactions.
+			txHash := tmhash.Sum(req.Tx)
+			app.dbBand.AddTransaction(
```
Comment (taobun) [inline chain/app/db_app.go]: Duplicate code? can be better

**Review by taobun — CHANGES_REQUESTED** [review]

File: chain/app/db_app.go [hunk 2]
```diff
@@ -155,25 +155,25 @@ func (app *dbBandApp) DeliverTx(req abci.RequestDeliverTx) (res abci.ResponseDel
...
+			stdTx.Fee.Gas,
+			stdTx.Fee.Amount,
+			stdTx.GetSigners()[0],
+			res.IsOK(),
+			app.DeliverContext.BlockHeight(),
+		)
 		if !res.IsOK() {
-			// TODO: We should not completely ignore failed transactions.
+			app.dbBand.HandleTransactionFail(stdTx, txHash)
+
```
Comment (taobun) [inline chain/app/db_app.go]: Remove this line

**Review by taobun — CHANGES_REQUESTED** [review]

**Review by taobun — APPROVED** [review]

**Review by sorawit — APPROVED** [review]
